Numpy :数値計算

In [1]:
import numpy as np

In [2]:
# ベクトルの定義
x = np.array([1, 2, 3])

In [3]:
x


array([1, 2, 3])

In [4]:
y = np.array([2, 3.9, 6.1])

In [5]:
y

array([2. , 3.9, 6.1])

In [6]:
x.mean()


2.0

In [7]:
y.mean()


4.0

In [8]:
# 中心化
xc = x - x.mean()

In [9]:
xc

array([-1.,  0.,  1.])

In [10]:
# 中心化
yc = y - y.mean()

In [11]:
yc

array([-2. , -0.1,  2.1])

## パラメータaの計算

In [15]:
# 要素ごとの掛け算（要素積）
# x * x
# cを加えセンタリングした時の計算
xx = xc * xc

In [18]:
xx


array([1., 0., 1.])

In [22]:
xy = xc * yc

In [23]:
xy

array([ 2. , -0. ,  2.1])

In [25]:
xx.sum()

2.0

In [26]:
xy.sum()

4.1

In [27]:
a = xy.sum()/xx.sum()

In [28]:
a


2.05